# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa87deca9acce6eee9da730157a97da638bb34e2072f3ced16af572322995621c3b10f7ccf96524e7f05605214c147d714db9189cf75f0d1cbee25c6c26c868

test:
  secret_key_base: 656d7bd601bb84bdb001f28de23a0cb32e7e028e98fb7d58e65d6678eaa3495225bcdd4ec8fc82a1a399d27bb69aa4722605174d7420cdbaeb9fd9cad0b5bccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
